CREATE CONSTRAINT movieIdConstraint IF NOT EXISTS FOR (m:Movie) REQUIRE m.id IS UNIQUE;

CREATE CONSTRAINT actorIdConstraint IF NOT EXISTS FOR (a:Actor) REQUIRE a.id IS UNIQUE;

CREATE CONSTRAINT countryIdConstraint IF NOT EXISTS FOR (c:Country) REQUIRE c.id IS UNIQUE;

CREATE CONSTRAINT keywordIdConstraint IF NOT EXISTS FOR (kw:Keyword) REQUIRE kw.id IS UNIQUE;
