@startchen Question 1a
entity Museum {
}

entity Department {
}

entity Collection {
}

entity "Art-Objects" as ArtObjects {
    acquisitionNumber <<key>>
    objectType
    "title" as title
    description
    dimension
    productionDate
    productionCountry
}

entity Paintings {

}

entity Sculptures {

}

entity Artist {

}

entity Period {

}

entity Exhibition {
    startDate
    endDate
    homeDepartment
}

relationship has {
}

Museum -1- has
Department -N- has

relationship belong {

}

Collection -1- belong
Department -1- belong

relationship in {

}

ArtObjects -N- in
Collection -1- in

ArtObjects ->- d { Paintings, Sculptures }

relationship "created by" as createdBy {

}

Artist -1- createdBy
createdBy -N- ArtObjects

relationship from {

}

ArtObjects -N- from 
from -1- Period

relationship "takes place" as takesPlace {

}

Exhibition -1- takesPlace
Museum -1- takesPlace

relationship exhibits {

}

Exhibition -1- exhibits
exhibits -N- Collection

relationship "borrowed for" as borrowed {
    
}

ArtObjects -N- borrowed
Exhibition -N- borrowed

relationship "taken from" as taken {
    duration
}

ArtObjects -N- taken
taken -N- Museum

@endchen